### ISSUE TITLE
Remove trained weight files

### ISSUE THREAD

**Issue by mlomnitz** [Lab41/cyphercat#49]
I think we should remove all these pre-trained model weights from the subdirectories 'networks100', 'networks10', 'model_weights' and 'pickles'.  Please make sure to make a local copy of them so we can safely delete
https://github.com/Lab41/cyphercat/tree/master/Classification_baselines/LibriSpeech

**Comment by ninalopatina** [comment]
Just seeing this now, but I removed these with my most recent pull request, yesterday
